### PR TITLE
Added SRS to project and removed wiki.txt.

### PR DESCRIPTION
**Pull request by Tirian33**
Merger of SRS branch into main branch:
Files effected are a New folder "SRS" which holds the SRS document and the basic EER diagram. The wiki.txt file is also being purged since we have wikis directly on the repository now.

### CODE REVIEW

**Comment by Tirian33** [comment]
SRS was pulled from google docs at 6:45 and had the EER diagram added. It seems alright to me and has no file conflicts with the target branch.

**Comment by asw241** [comment]
When downloading as .docx, formatting becomes distorted. Recommend the following:
- Take screenshot of flow diagram (Page 2), delete individual components and re-add diagram as image
- Remove parthentical instructions in all sections (I see one in section 2.2)
- Save and upload as .pdf

**Comment by Tirian33** [comment]
Turned the flow diagram into a png image and then imbedded it to the document.
And removed the instructions that were lingering in 2.2. 
Also swapped the file type to .pdf since we don't need that document edited routinely.

**Comment by RishitaGarg1** [comment]
I approve of this merge and I don’t see any issues or concerns which need immediate attention.

**Comment by debrahGh** [comment]
I approve of the merge.

**Pull request merged**
